- app/models/answer.rb
- db/migrate/20240604151959_create_answers.rb
- db/schema.rb
- test/models/answer_test.rb
> answer model created

- app/controllers/lessons_controller.rb
- app/models/lesson.rb
- db/migrate/20240604152720_create_lessons.rb
- db/schema.rb
- test/controllers/lessons_controller_test.rb
- test/models/lesson_test.rb
> lessons model and controller

- app/models/enrollment.rb
- db/migrate/20240604153152_create_enrollments.rb
- db/schema.rb
- test/models/enrollment_test.rb
> enrollment model created

- app/controllers/steps_controller.rb
- app/models/step.rb
- db/migrate/20240604161919_create_steps.rb
- db/schema.rb
- test/controllers/steps_controller_test.rb
- test/models/step_test.rb
> steps model and controller

- app/controllers/user_progress_controller.rb
- app/models/user_progress.rb
- db/migrate/20240604163803_create_user_progresses.rb
- db/schema.rb
- test/controllers/user_progress_controller_test.rb
- test/models/user_progress_test.rb
> created user progress model and controller

- app/models/lesson.rb
Lessons associations and validations
> lessons associations and validations

- app/models/answer.rb
- db/schema.rb
> added more validations to answer model

- app/controllers/user_progresses_controller.rb
Create action created. 
Preliminary update action created but will likely require more logic as app progresses
> user_progresses: create/update actions created.

- app/controllers/enrollments_controller.rb
> enrollments controller actions

- app/controllers/user_progresses_controller.rb
- app/views/courses/show.html.erb
> data bootstrap layout styling course show

- app/assets/stylesheets/components/_course_card.scss
- app/assets/stylesheets/components/_index.scss
- app/models/course.rb
- app/models/enrollment.rb
- app/models/user.rb
- app/views/courses/index.html.erb
- db/migrate/20240605202614_change_status_to_completed_in_enrollments.rb
- db/schema.rb
for review (Fred assisted, so some of the code might look foreign)
> logic and view for course-index page

- app/views/lessons/show.html.erb
- db/migrate/20240606150348_add_title_to_steps.rb
- db/schema.rb
- db/seeds.rb
> completed with more seed data

- app/javascript/controllers/answer_controller.js
- app/views/lessons/show.html.erb
answers can be clicked on and will display correct or incorrect as well as change the colour
> added the logic answer

- app/views/lessons/celebration.html.erb
> Styling celebration page

- app/views/lessons/show.html.erb
> light styling on lesson show page

- app/controllers/pages_controller.rb
- app/views/pages/dashboard.html.erb
- config/routes.rb
Logic for dashboard page coded + preliminary view. 
Further styling of view required for coherence with rest of app.
> Dashboard backend and view

- app/controllers/courses_controller.rb
- app/views/courses/index.html.erb
- app/views/courses/show.html.erb
so a user that is not signed up can check courses and the lessons, if he clicks on a lesson he will be redirected to sign up page
> added some logic for devise 

- app/controllers/user_progresses_controller.rb
- db/schema.rb
Coins feature now works.
1. +10 coins for starting a lesson
2. +50 coins for completing a lesson
3. +100 coins for completing a course
> coins feature works

- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- config/locales/simple_form.en.yml
- db/schema.rb
>  signup and login page

- app/assets/stylesheets/components/_cards.scss
- app/views/layouts/application.html.erb
- app/views/lessons/celebration.html.erb
> added streaks and coins cards to celebration page

- app/controllers/enrollments_controller.rb
- app/controllers/user_progresses_controller.rb
- app/javascript/controllers/coins_controller.js
- app/views/lessons/celebration.html.erb
Coins are now dynamically incremented on the celebration page.
Will require styling for coherence with the rest of the app. (some styling elements will be directly in the coins stimulus controller (JS))
> Increment coins

- app/assets/stylesheets/pages/_course_index.scss
- app/assets/stylesheets/pages/_course_show.scss
- app/assets/stylesheets/pages/_index.scss
- app/helpers/courses_helper.rb
- app/views/courses/show.html.erb
> updated styling for course show

- app/views/shared/_navbar.html.erb
> coins added to navbar with dropdown

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_btn_custom.scss
- app/assets/stylesheets/components/_cards.scss
- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/_sign_up.scss
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_links.html.erb
> styled sign up and login pages

- app/assets/stylesheets/components/_btn_custom.scss
- app/assets/stylesheets/components/_cards.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/pages/_course_show.scss
- app/assets/stylesheets/pages/_lesson_show.scss
- app/views/lessons/celebration.html.erb
- app/views/shared/_navbar.html.erb
- db/schema.rb
> updated nav

- db/seeds.rb
no enrollment or user progress is created in the seed, and only one user
> updated part of the seed

- app/models/user.rb
- db/migrate/20240613012738_add_default_values_to_coins_and_streak.rb
- db/schema.rb
> added default values of 0 for coins and streak through a migration

- app/assets/stylesheets/components/_circle.scss
- app/assets/stylesheets/components/_navbar.scss
- app/views/shared/_navbar.html.erb
> added avatar to nav

- app/assets/stylesheets/components/_progress_bar.scss
- app/assets/stylesheets/pages/_lesson_show.scss
- app/javascript/controllers/onboarding_controller.js
- app/javascript/controllers/progress_controller.js
- app/views/layouts/application.html.erb
- app/views/onboarding/_questionnaire_form.html.erb
- app/views/onboarding/step1.html.erb
- app/views/onboarding/step2.html.erb
- app/views/onboarding/step3.html.erb
- db/schema.rb
> Onboarding update

- db/seeds.rb
> new seed data for demo

- app/assets/stylesheets/pages/_lesson_show.scss
- app/helpers/steps_helper.rb
- app/views/lessons/show.html.erb
> displaying fill in the blanks answers as a grid

- app/javascript/controllers/purchase_controller.js
- app/views/lessons/show.html.erb
- app/views/shared/_navbar.html.erb
Bug fixed -- coins and avatar now update dynamically when user purchases something in store
> Debug avatar coins update

- app/assets/stylesheets/components/_cards.scss
- app/assets/stylesheets/components/_images.scss
- app/assets/stylesheets/components/_navbar.scss
- app/views/pages/home.html.erb
- app/views/shared/_navbar.html.erb
> Updating nav
